apiVersion: v1
kind: Secret
metadata:
  name: nodewarden-sm-token
stringData:
  token: |
    organization.ORG_ID.sa.SA_ID.TOKEN_ID
    nws_client_secret_here
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: nodewarden-app-secrets
spec:
  organizationId: ORG_ID
  secretName: app-from-nodewarden
  useSecretNames: true
  onlyMappedSecrets: false
  authToken:
    secretName: nodewarden-sm-token
    secretKey: token
